apiVersion: v1
kind: Service
metadata:
  name: nodejs-Service
  labels:
    app: icongen
spec:
  selector:
    app: icongen
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-Service
  labels:
    app: icongens
spec:
  selector:
    app: icongen
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP